### ISSUE TITLE
Update design style

### ISSUE THREAD

**Issue by MikkCZ** [clochix/FxStumbler#46]
Update design style according to the [Firefox OS Building Blocks](https://developer.mozilla.org/en-US/Apps/Design/Firefox_OS_building_blocks) for better look.

**Comment by clochix** [comment]
Thanks @MikkCZ, I didn't see there's a new version of the building blocks, using Web Components. I didn't like the implementation of first version of uilding bloks, so I didn't use it, but I'll have a look at this one.

**Comment by clochix** [comment]
Do you know if the new Web components are compatible with older versions of Fireofx OS ? I don't want to break the application for people using it with 1.x. I'll maybe create a new branch for a full reboot of the application.

**Comment by MikkCZ** [comment]
I think they aren't.
> Web components are supported in Firefox OS from v2.1 onwards, although most of them weren't actually implemented until v2.3. Be aware also that currently Web components won't work for Firefox OS apps below internal (certified) level. This restriction should be lessened in the future.

https://developer.mozilla.org/en-US/Apps/Design/Firefox_OS_building_blocks#Web_components_browser_support
