### ISSUE TITLE
L20n

### ISSUE THREAD

**Issue by MikkCZ** [clochix/FxStumbler#47]
If making full reboot in https://github.com/clochix/FxStumbler/issues/46, [L20n](http://l20n.org/) might be considered. I've tested it in pure HTML and works pretty smooth. But not sure about Transifex or other tools support.

**Comment by clochix** [comment]
I'm pretty happy with the awesome l10n I use for now, what would be the benefits of replacing it with l20n ?

**Comment by MikkCZ** [comment]
The main difference (for me) is, that the localizer can handle the localization logic (plurals, genders etc). [Here](http://l20n.org/learn/) is a few step long example. Some longer about texts are on [L20n - MozillaWiki](https://wiki.mozilla.org/L20n).

According to the information in [mozilla.tools.l10n](https://groups.google.com/forum/#!forum/mozilla.tools.l10n), it's being considered to use L20n in future Gaia versions.
