### ISSUE TITLE
Add FxStumbler to Marketplace

### ISSUE THREAD

**Issue by MikkCZ** [clochix/FxStumbler#49]
It would be very nice to have FxStumbler in Marketplace. I am use it and seems very stable for me.

https://marketplace.firefox.com/developers/

**Comment by clochix** [comment]
Hi @MikkCZ.

Unfortunately, It's not possible: this app uses API only available to certified apps, and certified apps can't be distributed through the marketplace. Only OEM could. See https://groups.google.com/forum/#!topic/mozilla.dev.marketplace/vY3Rj3tWXuU

Thanks for your nice feedback.
